const $=s=>document.querySelector(s),L='ABCDEFGHIJKLMNOPQRSTUVWXYZ',W='ADRENALIN',N=['green','blue','pink','orange'],C={green:'#69cf65',blue:'#2285df',pink:'#f73489',orange:'#ff8b25'},code=i=>[(i%5)+1,(Math.floor(i/5)%5)+1,((i*2)%5)+1,((i*3+1)%5)+1];let role='decoder',key=0,letter=0,last=0,startAt=0,penalty=0,tick,busy=false;
const wait=t=>new Promise(r=>setTimeout(r,t)),fmt=n=>{let s=n/1000|0;return`${String(s/60|0).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{role=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('selected',x===b))});
$('#start').onclick=()=>{$('#roles').classList.add('hidden');$('#game').classList.remove('hidden');startAt=Date.now();penalty=0;letter=0;last=0;$('#timer').textContent='00:00';if(role==='decoder')tick=setInterval(()=>$('#timer').textContent=fmt(Date.now()-startAt+penalty),250);render();if(role!=='decoder')opening()};
function dots(c){return`<div style="display:flex;justify-content:center;gap:10px">${N.map((n,i)=>`<i style="display:grid;place-items:center;width:34px;height:34px;border-radius:50%;background:${C[n]};color:#061533;font-style:normal;font-weight:900">${c[i]}</i>`).join('')}</div>`}
function render(){let d=role==='decoder';$('#role-card').innerHTML=d?'<b>_ _ _ _ _ _ _ _ _</b><span>Decode the word.</span>':`<b>YOUR COLOUR: ${role.toUpperCase()}</b><span>Watch all colours; count only ${role.toUpperCase()}.</span>`;$('#letter-key').classList.toggle('hidden',!d);if(d){$('#letter-key').innerHTML=[...L].map((x,i)=>`<button class="letter ${i===key?'selected':''}" data-key="${i}">${x}</button>`).join('');let c=code(key);$('#game-view').innerHTML=`<div class="code-card"><strong>${L[key]}</strong>${dots(c)}</div><input id="guess" class="guess" placeholder="TYPE THE WORD"><button id="decode" style="display:block;margin:10px auto">DECODE WORD</button><p id="result" style="text-align:center"></p>`}else{$('#game-view').innerHTML=`<div style="display:grid;justify-items:center;gap:14px;text-align:center;padding-top:30px"><p id="letter" class="status">STARTING IN 10</p><div id="lamp" class="lamp"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;width:100%"><button id="again" disabled>AGAIN</button><button id="next" disabled>NEXT</button></div><button id="restart">RESTART</button></div>`}}
$('#letter-key').onclick=e=>{let b=e.target.closest('button');if(b){key=+b.dataset.key;render()}};
async function flash(index){let lamp=$('#lamp'),pool=[];code(L.indexOf(W[index])).forEach((n,i)=>{for(let j=0;j<n;j++)pool.push(N[i])});let stream=[],lastColour='';while(pool.length){let choices=[...new Set(pool.filter(c=>c!==lastColour))];if(!choices.length)choices=[...new Set(pool)];let colour=choices[Math.floor(Math.random()*choices.length)];pool.splice(pool.indexOf(colour),1);stream.push(colour);lastColour=colour}for(const colour of stream){lamp.style.setProperty('--colour',C[colour]);lamp.classList.add('flash');await wait(300);lamp.classList.remove('flash');await wait(240)}}
async function before(label){for(let s=5;s>0;s--){$('#letter').textContent=`${label} IN ${s}`;await wait(1000)}}
function lock(on){$('#again').disabled=on;$('#next').disabled=on}
async function opening(){for(let s=10;s>0;s--){$('#letter').textContent=`STARTING IN ${s}`;await wait(1000)}busy=true;lock(true);$('#letter').textContent='LETTER 1 / 9';await flash(0);last=0;letter=1;busy=false;$('#letter').textContent='LETTER 1 COMPLETE';lock(false)}
async function next(){if(busy||letter>=W.length)return;busy=true;lock(true);await before('NEXT');$('#letter').textContent=`LETTER ${letter+1} / 9`;await flash(letter);last=letter;letter++;busy=false;$('#letter').textContent=`LETTER ${last+1} COMPLETE`;$('#again').disabled=false;$('#next').disabled=letter>=W.length}
async function again(){if(busy)return;penalty+=10000;$('#timer').textContent=fmt(penalty);busy=true;lock(true);await before('AGAIN');$('#letter').textContent=`LETTER ${last+1} / 9`;await flash(last);busy=false;$('#letter').textContent=`LETTER ${last+1} COMPLETE`;$('#again').disabled=false;$('#next').disabled=letter>=W.length}
document.addEventListener('click',e=>{if(e.target.id==='next')next();if(e.target.id==='again')again();if(e.target.id==='restart'&&!busy){letter=0;last=0;opening()}if(e.target.id==='decode'){if($('#guess').value.trim().toUpperCase()===W){clearInterval(tick);$('#game-view').innerHTML=`<div style="display:grid;place-items:center;text-align:center;min-height:45vh"><h1>WORD<br><span>DECODED!</span></h1><p class="status">TIME TAKEN: ${fmt(Date.now()-startAt+penalty)}</p></div>`}else{penalty+=10000;$('#result').textContent='WRONG WORD - 10 SECONDS ADDED.'}}});
