const $ = (s) => document.querySelector(s);
const L = "ABCDEFGHIJKLMNOPQRSTUVWXYZ", W = "ADRENALIN";
const C = { green: "#69cf65", blue: "#2285df", pink: "#f73489", orange: "#ff8b25" };
const code = (i) => [((i * 2) % 5) + 1, ((i * 3 + 1) % 5) + 1, ((i * 4 + 2) % 5) + 1, ((i * 5 + 3) % 5) + 1];
let role = "decoder", key = 0;
document.querySelectorAll("[data-r]").forEach((b) => b.onclick = () => { role = b.dataset.r; document.querySelectorAll("[data-r]").forEach((x) => x.classList.toggle("selected", x === b)); });
$("#start").onclick = () => { $("#roles").classList.add("hidden"); $("#game").classList.remove("hidden"); render(); };
function render() { const d = role === "decoder"; $("#role").textContent = d ? "DECODER" : role.toUpperCase(); $("#card").innerHTML = d ? "<b>_ _ _ _ _ _ _ _ _</b><span>Decode the word.</span>" : `<b>YOUR COLOUR: ${role.toUpperCase()}</b><span>Choose a number and count.</span>`; if (d) { $("#choices").innerHTML = [...L].map((x,i)=>`<button class="letter ${i===key?"selected":""}" data-k="${i}">${x}</button>`).join(""); const c=code(key); $("#view").innerHTML=`<div class="code-card"><strong>${L[key]}</strong><span>GREEN ${c[0]} · BLUE ${c[1]} · PINK ${c[2]} · ORANGE ${c[3]}</span></div><input id="guess" class="guess" placeholder="TYPE THE WORD"><button id="decode">DECODE WORD</button><p id="result"></p>`; } else { $("#choices").innerHTML=[...W].map((_,i)=>`<button class="position" data-n="${i}">${i+1}</button>`).join(""); $("#view").innerHTML='<div id="lamp" class="lamp"></div>'; $("#lamp").style.borderColor=C[role]; } }
$("#choices").onclick=async(e)=>{const b=e.target.closest("button");if(!b)return;if(role==="decoder"){key=+b.dataset.k;render();return;}const count=code(L.indexOf(W[+b.dataset.n]))[["green","blue","pink","orange"].indexOf(role)],lamp=$("#lamp"),colour=C[role];for(let i=0;i<count;i++){lamp.classList.add("flash");lamp.style.setProperty("background",colour,"important");lamp.style.setProperty("box-shadow",`0 0 45px ${colour}, 0 0 85px ${colour}`,"important");await new Promise(r=>setTimeout(r,300));lamp.classList.remove("flash");lamp.style.removeProperty("background");lamp.style.removeProperty("box-shadow");await new Promise(r=>setTimeout(r,240));}};
document.addEventListener("click",e=>{if(e.target.id==="decode")$("#result").textContent=$("#guess").value.trim().toUpperCase()===W?"WORD DECODED!":"TRY AGAIN";});
